spring:
  management:
    security:
      enabled: false
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_ma45
    username: "postgres"
    password: "248842"
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      driver-class-name: "org.postgresql.Driver"
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  flyway.baseline-on-migrate: true
  profiles:
    active: rest

no-sql:
  mongo:
    name: local
    host: localhost
    port: 27017
